# Usar uma imagem oficial do Python como base
FROM python:3.10-slim

# Define o diretório de trabalho no contêiner
WORKDIR /app

# Copia o script Python para o diretório de trabalho
COPY . /app

# Comando para executar o script principal
CMD ["python", "main.py"]

